# Generated by Django 5.2 on 2025-05-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='authors/default_author.jpg', upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='books/default_cover.jpg', upload_to='books/covers/'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(default='publishers/default_publisher.png', upload_to='publishers/'),
        ),
    ]
