# Generated by Django 5.1.7 on 2025-05-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_pdf_file_alter_author_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publisher',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='books/covers/default_cover.jpg', upload_to='books/covers/'),
        ),
    ]
